server:
  port: 8091

spring:
  config:
    import: optional:configserver:http://localhost:8085
  datasource:
    url: jdbc:mysql://localhost:3306/algo-nexus-courseService?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: COURSE-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

