server:
  port: 8084


spring:
  config:
    import: optional:configserver:http://localhost:8085
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:4200'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: USER-SERVICE-cloudinary
          uri: lb://USER-SERVICE
          predicates:
            - Path=/cloudinary/**


        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**


        - id: PROBLEM-SERVICE
          uri: lb://PROBLEM-SERVICE
          predicates:
            - Path=/problem/**

        - id: PROBLEM-SERVICE-category
          uri: lb://PROBLEM-SERVICE
          predicates:
            - Path=/category/**

        - id: PROBLEM-SERVICE-difficulty
          uri: lb://PROBLEM-SERVICE
          predicates:
            - Path=/difficulty/**


        - id: TESTCASE-SERVICE
          uri: lb://TESTCASE-SERVICE
          predicates:
            - Path=/test-case/**


        - id: PROBLEM-SUBMISSION-SERVICE
          uri: lb://PROBLEM-SUBMISSION-SERVICE
          predicates:
            - Path=/submit-solution/**


        - id: COURSE-SERVICE
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/courses/**

        - id: COURSE-SERVICE-videos
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/videos/**

        - id: DAILY-PROBLEM-SERVICE
          uri: lb://DAILY-PROBLEM-SERVICE
          predicates:
            - Path=/daily-problem/**

        - id: DAILY-PROBLEM-SERVICE-streak
          uri: lb://DAILY-PROBLEM-SERVICE
          predicates:
            - Path=/streak/**


  application:
    name: API-GATEWAY



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
