server:
  port: 8087

spring:
  profiles:
    active: dev
    servlet:
      multipart:
        max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

servlet:
  context-path: /api/v1
