server:
  port: 8088


spring:
  config:
    import: optional:configserver:http://localhost:8085
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: algo-nexus-problemService
      auto-index-creation: true
      auto-create-indexes: true

  application:
    name: PROBLEM-SERVICE

judge0:
  base_url: "http://34.93.145.38:2358"
