server:
  port: 8090


spring:
  config:
    import: optional:configserver:http://localhost:8085
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: algo-nexus-problemSubmissionService
      auto-index-creation: true
      auto-create-indexes: true

  application:
    name: PROBLEM-SUBMISSION-SERVICE

